version: "3.9"
services:
  zoomwebhookd:
    build:
      context: ..
      dockerfile: docker/Dockerfile.zoom
    container_name: zoomwebhookd
    environment:
      - PORT=8080
      - ZOOM_WEBHOOK_SECRET_TOKEN=${ZOOM_WEBHOOK_SECRET_TOKEN}
    volumes:
      - ./configs/zoomapp.yaml:/app/configs/zoomapp.yaml:ro
      - ../outbox:/app/outbox
      - ../data:/app/data
      - ../logs:/app/logs
    command: ["./zoomwebhookd","--config","configs/zoomapp.yaml","--fastpath"]
    ports:
      - "8080:8080"
    networks: [observability]

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    command: ["--config.file=/etc/prometheus/prometheus.yml","--storage.tsdb.retention.time=2d"]
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks: [observability]

  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    command: ["-config.file=/etc/loki/local-config.yaml"]
    volumes:
      - ./configs/loki-config.yml:/etc/loki/local-config.yaml:ro
      - ../loki-data:/loki
    ports:
      - "3100:3100"
    networks: [observability]

  promtail:
    image: grafana/promtail:2.9.8
    container_name: promtail
    command: ["-config.file=/etc/promtail/config.yml"]
    volumes:
      - ./configs/promtail-config.yml:/etc/promtail/config.yml:ro
      - ../logs:/var/log/webhookd:ro
    depends_on: [loki]
    networks: [observability]

  tempo:
    image: grafana/tempo:2.5.0
    container_name: tempo
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    volumes:
      - ./configs/tempo.yaml:/etc/tempo/tempo.yaml:ro
      - ../tempo-data:/var/lib/tempo
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
    networks: [observability]

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on: [prometheus, loki, tempo]
    networks: [observability]

networks:
  observability:
    driver: bridge
