FROM golang:1.23 as build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o zoomwebhookd ./cmd/zoomwebhookd

FROM gcr.io/distroless/base-debian12:nonroot
WORKDIR /app
COPY --from=build /app/zoomwebhookd /app/zoomwebhookd
COPY docker/configs/zoomapp.yaml /app/configs/zoomapp.yaml
USER nonroot:nonroot
EXPOSE 8080
ENTRYPOINT ["/app/zoomwebhookd"]
