name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: '1.23.x', check-latest: true, cache: true }
      - run: go mod tidy
      - run: go build ./...
      - run: go test ./... -v -count=1
