name: govulncheck
on: [push, pull_request]
permissions: { contents: read, security-events: write }
jobs:
  vuln:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: '1.23.x', cache: true }
      
      - run: go mod tidy
      - run: go build ./...
      - run: go list ./...

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Run govulncheck
        run: govulncheck -format sarif -out govulncheck.sarif ./... || true

      - name: Upload SARIF report
        if: ${{ hashFiles('govulncheck.sarif') != '' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: govulncheck.sarif
